name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        if: hashFiles(package.json) != 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & Lint (Node)
        if: hashFiles(package.json) != 
        run: |
          npm ci
          npm run lint || true
      - name: Setup Python
        if: hashFiles(requirements.txt) !=  || hashFiles(pyproject.toml) != 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Lint (Python)
        if: hashFiles(requirements.txt) !=  || hashFiles(pyproject.toml) != 
        run: |
          pip install black flake8
          black --check . || true
          flake8 . || true

